"""allowed_ips unique

Revision ID: 1bfc90889568
Revises: e35cd4ae11b0
Create Date: 2024-08-20 02:42:30.437694

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bfc90889568"
down_revision: Union[str, None] = "e35cd4ae11b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq__peer__allowed_ips"), "peer", ["allowed_ips"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__peer__allowed_ips"), "peer", type_="unique")
    # ### end Alembic commands ###
