"""peer model

Revision ID: 603ec875b0b7
Revises: 
Create Date: 2024-08-17 17:19:54.544702

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "603ec875b0b7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("private_key", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("allowed_ips", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__peer")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("peer")
    # ### end Alembic commands ###
