"""wgo_key model

Revision ID: e27326e27605
Revises: 603ec875b0b7
Create Date: 2024-08-17 17:20:52.723006

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e27326e27605"
down_revision: Union[str, None] = "603ec875b0b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wg0_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("private_key", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__wg0_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wg0_key")
    # ### end Alembic commands ###
