"""allowed_ips as INET

Revision ID: e35cd4ae11b0
Revises: c5049efef47d
Create Date: 2024-08-18 00:14:50.089190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e35cd4ae11b0'
down_revision: Union[str, None] = 'c5049efef47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peer', 'allowed_ips',
               existing_type=postgresql.CIDR(),
               type_=postgresql.INET(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peer', 'allowed_ips',
               existing_type=postgresql.INET(),
               type_=postgresql.CIDR(),
               existing_nullable=False)
    # ### end Alembic commands ###
